#!/usr/bin/env python3
"""Audit the integration-only Surefire allowlist using Spring/Testcontainers ancestry.
No production-code exclusions. Run --write after adding an integration class.
"""
from pathlib import Path
import re
import sys
root = Path(__file__).resolve().parents[1]
classes = {}
for path in sorted((root / 'src/test/java').rglob('*.java')):
    source = re.sub(r'/\*.*?\*/|//[^\n]*', '', path.read_text(), flags=re.S)
    match = re.search(r'\b(abstract\s+)?class\s+(\w+)(?:\s+extends\s+(\w+))?', source)
    if match:
        if match[2] in classes:
            sys.exit(f'Duplicate test class name requires explicit resolution: {match[2]}')
        classes[match[2]] = (path, bool(match[1]), match[3], bool(re.search(r'@(?:SpringBootTest|Testcontainers)\b', source)))
def integration(name, seen=()):
    if name not in classes or name in seen:
        return False
    _, _, parent, annotated = classes[name]
    return annotated or integration(parent, (*seen, name))
selected = sorted(str(data[0].relative_to(root / 'src/test/java'))
                  for name, data in classes.items() if not data[1] and integration(name))
content = '# Integration-only allowlist; generated by scripts/integration-suite.py --write\n' + '\n'.join(selected) + '\n'
manifest = root / 'src/test/integration-tests.includes'
if '--write' in sys.argv:
    manifest.write_text(content)
elif not manifest.exists() or manifest.read_text() != content:
    sys.exit('Integration allowlist is stale. Run python3 scripts/integration-suite.py --write and review it.')
print(f'{len(selected)} concrete integration classes; no unit-test naming heuristic used.')
